### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by maadi7** [VishalIITP/CodeTalkBackend#33]
Implement rate limiting to protect your API from abuse or potential DoS attacks. The 'express-rate-limit' middleware is a popular choice.

@VishalIITP this is security measure, would you like me to work on this issue.

**Comment by VishalIITP** [comment]
@maadi7 You can start working on this one, assigned to you.

**Comment by maadi7** [comment]
@VishalIITP Please check and merge this.

**Comment by maadi7** [comment]
@VishalIITP please check the PR.

**Comment by VishalIITP** [comment]
> @VishalIITP please check the PR.

awarded you 6 points for this one. Keep contributing!
